from config import get_conn
import oracledb

DDL_MONITOR_TABLE = """
CREATE TABLE ENGENHARIA.FIELDLOGGER_MONITOR (
  ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  TS              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  TEMP_RAW        NUMBER,
  CORRENTE_RAW    NUMBER,
  TEMPERATURA_C   NUMBER,
  CORRENTE        NUMBER,
  BOTAO_START     NUMBER(1),
  TAMPA_DESCARGA  NUMBER(1),
  BATCH_ID        NUMBER,
  COMPOSTO_COD    NUMBER,
  COMPOSTO        VARCHAR2(200),
  LOTE            VARCHAR2(120),
  OBSERVACOES     VARCHAR2(500),
  SRC             VARCHAR2(50)
)
"""

DDL_COMPOSTOS_TABLE = """
CREATE TABLE ENGENHARIA.FIELDLOGGER_COMPOSTOS (
  CODPROD        NUMBER PRIMARY KEY,
  DESCRICAO      VARCHAR2(200) NOT NULL,
  CODGRUPOPROD   NUMBER NOT NULL,
  ATIVO          CHAR(1) DEFAULT 'S' NOT NULL,
  IMPORTADO_EM   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
)
"""

DDL_INDEXES = [
    (
        """
        CREATE INDEX ENGENHARIA.IX_FL_MONITOR_TS
        ON ENGENHARIA.FIELDLOGGER_MONITOR (TS)
        """,
        "indice TS",
    ),
    (
        """
        CREATE INDEX ENGENHARIA.IX_FL_MONITOR_BATCH_ID
        ON ENGENHARIA.FIELDLOGGER_MONITOR (BATCH_ID)
        """,
        "indice BATCH_ID",
    ),
    (
        """
        CREATE INDEX ENGENHARIA.IX_FL_MONITOR_COMP_COD
        ON ENGENHARIA.FIELDLOGGER_MONITOR (COMPOSTO_COD)
        """,
        "indice COMPOSTO_COD",
    ),
    (
        """
        CREATE INDEX ENGENHARIA.IX_FL_COMPOSTOS_DESC
        ON ENGENHARIA.FIELDLOGGER_COMPOSTOS (DESCRICAO)
        """,
        "indice COMPOSTOS_DESCRICAO",
    ),
]


def _exec_create(cur, ddl: str, name: str):
    try:
        cur.execute(ddl)
        print(f"{name} criado(a) com sucesso.")
    except oracledb.DatabaseError as e:
        error_obj, = e.args
        if error_obj.code == 955:
            print(f"{name} ja existe.")
        else:
            raise


def create_objects():
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute("SELECT 'OK' FROM dual")
            print("Conexao Oracle OK")

            _exec_create(cur, DDL_MONITOR_TABLE, "Tabela FIELDLOGGER_MONITOR")
            _exec_create(cur, DDL_COMPOSTOS_TABLE, "Tabela FIELDLOGGER_COMPOSTOS")

            for ddl, name in DDL_INDEXES:
                _exec_create(cur, ddl, name)

        conn.commit()


if __name__ == "__main__":
    create_objects()
