-- sql/001_create_batch_tables.sql
-- Cria tabela de ciclos (batches) e vinculo no monitor.

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE ENGENHARIA.FIELDLOGGER_MONITOR ADD (BATCH_ID NUMBER)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE ENGENHARIA.FIELDLOGGER_BATCHES (
      BATCH_ID       NUMBER PRIMARY KEY,
      START_TS       TIMESTAMP NOT NULL,
      END_TS         TIMESTAMP NULL,
      DURATION_S     NUMBER NULL,
      MAX_TEMP       NUMBER NULL,
      MAX_CORRENTE   NUMBER NULL,
      AVG_TEMP       NUMBER NULL,
      AVG_CORRENTE   NUMBER NULL,
      SIGNATURE      VARCHAR2(64) NULL,
      OP             VARCHAR2(50) NULL,
      OPERADOR       VARCHAR2(80) NULL,
      OBSERVACOES    VARCHAR2(4000) NULL,
      CREATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX ENGENHARIA.IX_FL_BATCHES_START_TS ON ENGENHARIA.FIELDLOGGER_BATCHES (START_TS)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX ENGENHARIA.IX_FL_BATCHES_END_TS ON ENGENHARIA.FIELDLOGGER_BATCHES (END_TS)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX ENGENHARIA.IX_FL_BATCHES_OP ON ENGENHARIA.FIELDLOGGER_BATCHES (OP)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX ENGENHARIA.IX_FL_MONITOR_BATCH_ID ON ENGENHARIA.FIELDLOGGER_MONITOR (BATCH_ID)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    ALTER TABLE ENGENHARIA.FIELDLOGGER_MONITOR
    ADD CONSTRAINT FK_FL_MONITOR_BATCHES
    FOREIGN KEY (BATCH_ID)
    REFERENCES ENGENHARIA.FIELDLOGGER_BATCHES (BATCH_ID)
    ENABLE NOVALIDATE
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-2261, -2275) THEN
      RAISE;
    END IF;
END;
/
